"""Data models for the PriceAdvisor module."""
from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional


class SuggestionStatus(str, Enum):
    """Lifecycle status of a price suggestion."""
    PENDING = "pending"
    VALIDATED = "validated"
    NEEDS_REVIEW = "needs_review"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    FAILED = "failed"


@dataclass
class PriceRecord:
    """A single historical price entry stored in the price database."""
    id: Optional[int] = None
    item_name: str = ""
    item_code: str = ""
    unit: str = ""
    unit_price: Optional[float] = None
    total_price: Optional[float] = None
    quantity: Optional[float] = None
    project_name: str = ""
    project_type: str = ""
    year: Optional[int] = None
    region: str = ""
    brand: str = ""
    origin: str = ""
    material_spec: str = ""
    embedding: Optional[list[float]] = None
    source_file: str = ""
    created_at: Optional[str] = None
    status: str = "active"

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        data.pop("embedding", None)  # Don't serialize large vectors
        return data

    @property
    def description_text(self) -> str:
        """Concatenated text used for embedding generation."""
        parts = [self.item_name]
        if self.item_code:
            parts.append(f"Mã: {self.item_code}")
        if self.unit:
            parts.append(f"ĐVT: {self.unit}")
        if self.material_spec:
            parts.append(f"Quy cách: {self.material_spec}")
        if self.brand:
            parts.append(f"Thương hiệu: {self.brand}")
        return " | ".join(parts)


@dataclass
class SimilarItem:
    """A historical price record found via vector search."""
    record: PriceRecord
    similarity_score: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "item_name": self.record.item_name,
            "item_code": self.record.item_code,
            "unit": self.record.unit,
            "unit_price": self.record.unit_price,
            "quantity": self.record.quantity,
            "year": self.record.year,
            "region": self.record.region,
            "brand": self.record.brand,
            "material_spec": self.record.material_spec,
            "similarity": round(self.similarity_score, 4),
        }


@dataclass
class PriceSuggestion:
    """A price suggestion generated by the LLM for a single BOQ item."""
    item_id: str = ""
    item_name: str = ""
    unit: str = ""
    min_price: Optional[float] = None
    max_price: Optional[float] = None
    suggested_price: Optional[float] = None
    confidence: float = 0.0
    reasoning: str = ""
    market_trend: str = ""                       # Nhận xét xu hướng thị trường từ LLM
    price_comment: str = ""                      # Nhận xét ngắn về giá dự đoán
    similar_items: list[SimilarItem] = field(default_factory=list)
    status: SuggestionStatus = SuggestionStatus.PENDING
    error_message: str = ""
    llm_provider: str = ""
    llm_model: str = ""
    tokens_used: int = 0
    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(timespec="seconds")
    )

    def to_dict(self) -> dict[str, Any]:
        return {
            "item_id": self.item_id,
            "item_name": self.item_name,
            "unit": self.unit,
            "min_price": self.min_price,
            "max_price": self.max_price,
            "suggested_price": self.suggested_price,
            "confidence": round(self.confidence, 4),
            "reasoning": self.reasoning,
            "market_trend": self.market_trend,
            "price_comment": self.price_comment,
            "similar_items": [item.to_dict() for item in self.similar_items],
            "status": self.status.value,
            "error_message": self.error_message,
            "llm_provider": self.llm_provider,
            "llm_model": self.llm_model,
            "tokens_used": self.tokens_used,
            "created_at": self.created_at,
        }


@dataclass
class AdvisorResult:
    """Aggregated result from a PriceAdvisor run across multiple items."""
    job_id: str = ""
    suggestions: list[PriceSuggestion] = field(default_factory=list)
    total_items_analyzed: int = 0
    items_with_suggestions: int = 0
    items_failed: int = 0
    total_tokens_used: int = 0
    elapsed_seconds: float = 0.0
    warnings: list[str] = field(default_factory=list)
    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(timespec="seconds")
    )

    def to_dict(self) -> dict[str, Any]:
        return {
            "job_id": self.job_id,
            "suggestions": [s.to_dict() for s in self.suggestions],
            "summary": {
                "total_items_analyzed": self.total_items_analyzed,
                "items_with_suggestions": self.items_with_suggestions,
                "items_failed": self.items_failed,
                "total_tokens_used": self.total_tokens_used,
                "elapsed_seconds": round(self.elapsed_seconds, 3),
            },
            "warnings": self.warnings,
            "created_at": self.created_at,
        }
